// Generated by gencpp from file task2/ImageRecognitionRequest.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_IMAGERECOGNITIONREQUEST_H
#define TASK2_MESSAGE_IMAGERECOGNITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task2
{
template <class ContainerAllocator>
struct ImageRecognitionRequest_
{
  typedef ImageRecognitionRequest_<ContainerAllocator> Type;

  ImageRecognitionRequest_()
    : request(false)  {
    }
  ImageRecognitionRequest_(const ContainerAllocator& _alloc)
    : request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::task2::ImageRecognitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task2::ImageRecognitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageRecognitionRequest_

typedef ::task2::ImageRecognitionRequest_<std::allocator<void> > ImageRecognitionRequest;

typedef boost::shared_ptr< ::task2::ImageRecognitionRequest > ImageRecognitionRequestPtr;
typedef boost::shared_ptr< ::task2::ImageRecognitionRequest const> ImageRecognitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task2::ImageRecognitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task2::ImageRecognitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task2::ImageRecognitionRequest_<ContainerAllocator1> & lhs, const ::task2::ImageRecognitionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task2::ImageRecognitionRequest_<ContainerAllocator1> & lhs, const ::task2::ImageRecognitionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::ImageRecognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::ImageRecognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::ImageRecognitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f7e5ad6ab0ddf42c5727a195315a470";
  }

  static const char* value(const ::task2::ImageRecognitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f7e5ad6ab0ddf42ULL;
  static const uint64_t static_value2 = 0xc5727a195315a470ULL;
};

template<class ContainerAllocator>
struct DataType< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task2/ImageRecognitionRequest";
  }

  static const char* value(const ::task2::ImageRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool request\n"
;
  }

  static const char* value(const ::task2::ImageRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageRecognitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task2::ImageRecognitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task2::ImageRecognitionRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK2_MESSAGE_IMAGERECOGNITIONREQUEST_H
