// Generated by gencpp from file task2/ImageRecognitionResponse.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_IMAGERECOGNITIONRESPONSE_H
#define TASK2_MESSAGE_IMAGERECOGNITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task2
{
template <class ContainerAllocator>
struct ImageRecognitionResponse_
{
  typedef ImageRecognitionResponse_<ContainerAllocator> Type;

  ImageRecognitionResponse_()
    : wonted(false)
    , prize(0)
    , color()  {
    }
  ImageRecognitionResponse_(const ContainerAllocator& _alloc)
    : wonted(false)
    , prize(0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _wonted_type;
  _wonted_type wonted;

   typedef int32_t _prize_type;
  _prize_type prize;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::task2::ImageRecognitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task2::ImageRecognitionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImageRecognitionResponse_

typedef ::task2::ImageRecognitionResponse_<std::allocator<void> > ImageRecognitionResponse;

typedef boost::shared_ptr< ::task2::ImageRecognitionResponse > ImageRecognitionResponsePtr;
typedef boost::shared_ptr< ::task2::ImageRecognitionResponse const> ImageRecognitionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task2::ImageRecognitionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task2::ImageRecognitionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task2::ImageRecognitionResponse_<ContainerAllocator1> & lhs, const ::task2::ImageRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.wonted == rhs.wonted &&
    lhs.prize == rhs.prize &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task2::ImageRecognitionResponse_<ContainerAllocator1> & lhs, const ::task2::ImageRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::ImageRecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::ImageRecognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::ImageRecognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b4891469b4908a9aedcfa9c179e8f57";
  }

  static const char* value(const ::task2::ImageRecognitionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b4891469b4908a9ULL;
  static const uint64_t static_value2 = 0xaedcfa9c179e8f57ULL;
};

template<class ContainerAllocator>
struct DataType< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task2/ImageRecognitionResponse";
  }

  static const char* value(const ::task2::ImageRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool wonted\n"
"int32 prize\n"
"string color\n"
;
  }

  static const char* value(const ::task2::ImageRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wonted);
      stream.next(m.prize);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageRecognitionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task2::ImageRecognitionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task2::ImageRecognitionResponse_<ContainerAllocator>& v)
  {
    s << indent << "wonted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wonted);
    s << indent << "prize: ";
    Printer<int32_t>::stream(s, indent + "  ", v.prize);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK2_MESSAGE_IMAGERECOGNITIONRESPONSE_H
