// Generated by gencpp from file task2/ImageRecognition.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_IMAGERECOGNITION_H
#define TASK2_MESSAGE_IMAGERECOGNITION_H

#include <ros/service_traits.h>


#include <task2/ImageRecognitionRequest.h>
#include <task2/ImageRecognitionResponse.h>


namespace task2
{

struct ImageRecognition
{

typedef ImageRecognitionRequest Request;
typedef ImageRecognitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageRecognition
} // namespace task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task2::ImageRecognition > {
  static const char* value()
  {
    return "650cece1c17a57944253f7b077548754";
  }

  static const char* value(const ::task2::ImageRecognition&) { return value(); }
};

template<>
struct DataType< ::task2::ImageRecognition > {
  static const char* value()
  {
    return "task2/ImageRecognition";
  }

  static const char* value(const ::task2::ImageRecognition&) { return value(); }
};


// service_traits::MD5Sum< ::task2::ImageRecognitionRequest> should match
// service_traits::MD5Sum< ::task2::ImageRecognition >
template<>
struct MD5Sum< ::task2::ImageRecognitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task2::ImageRecognition >::value();
  }
  static const char* value(const ::task2::ImageRecognitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::ImageRecognitionRequest> should match
// service_traits::DataType< ::task2::ImageRecognition >
template<>
struct DataType< ::task2::ImageRecognitionRequest>
{
  static const char* value()
  {
    return DataType< ::task2::ImageRecognition >::value();
  }
  static const char* value(const ::task2::ImageRecognitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task2::ImageRecognitionResponse> should match
// service_traits::MD5Sum< ::task2::ImageRecognition >
template<>
struct MD5Sum< ::task2::ImageRecognitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task2::ImageRecognition >::value();
  }
  static const char* value(const ::task2::ImageRecognitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::ImageRecognitionResponse> should match
// service_traits::DataType< ::task2::ImageRecognition >
template<>
struct DataType< ::task2::ImageRecognitionResponse>
{
  static const char* value()
  {
    return DataType< ::task2::ImageRecognition >::value();
  }
  static const char* value(const ::task2::ImageRecognitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK2_MESSAGE_IMAGERECOGNITION_H
