// Generated by gencpp from file task2/Ring.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_RING_H
#define TASK2_MESSAGE_RING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task2
{
template <class ContainerAllocator>
struct Ring_
{
  typedef Ring_<ContainerAllocator> Type;

  Ring_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , color()  {
    }
  Ring_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::task2::Ring_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task2::Ring_<ContainerAllocator> const> ConstPtr;

}; // struct Ring_

typedef ::task2::Ring_<std::allocator<void> > Ring;

typedef boost::shared_ptr< ::task2::Ring > RingPtr;
typedef boost::shared_ptr< ::task2::Ring const> RingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task2::Ring_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task2::Ring_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task2::Ring_<ContainerAllocator1> & lhs, const ::task2::Ring_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task2::Ring_<ContainerAllocator1> & lhs, const ::task2::Ring_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task2::Ring_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::Ring_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::Ring_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::Ring_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::Ring_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::Ring_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task2::Ring_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edbf2a91471737255f89bab92ee5995f";
  }

  static const char* value(const ::task2::Ring_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedbf2a9147173725ULL;
  static const uint64_t static_value2 = 0x5f89bab92ee5995fULL;
};

template<class ContainerAllocator>
struct DataType< ::task2::Ring_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task2/Ring";
  }

  static const char* value(const ::task2::Ring_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task2::Ring_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"string color\n"
;
  }

  static const char* value(const ::task2::Ring_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task2::Ring_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ring_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task2::Ring_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task2::Ring_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK2_MESSAGE_RING_H
