(cl:defpackage task2-srv
  (:use )
  (:export
   "IMAGERECOGNITION"
   "<IMAGERECOGNITION-REQUEST>"
   "IMAGERECOGNITION-REQUEST"
   "<IMAGERECOGNITION-RESPONSE>"
   "IMAGERECOGNITION-RESPONSE"
  ))

